export type {
  Patient,
  Order,
  OrderStatus,
  Consultation,
  CoachingLog,
  Clinic,
  ClinicConfig,
  User,
  Role,
  ClinicId,
  Incident,
  IncidentType,
  IncidentSeverity,
  IncidentStatus,
  Complaint,
  ComplaintSeverity,
  ComplaintStatus,
  Amendment,
  GPLetter,
  GPLetterStatus,
  GPLetterTemplate,
  MondayItem,
  MondayBoardState,
} from "@/lib/api/mock";
