export type {
  Patient,
  Order,
  OrderStatus,
  Consultation,
  CoachingLog,
  Clinic,
  ClinicConfig,
  ClinicTeamMember,
  ConsentTemplate,
  HolidayEntry,
  ConsultationTypeConfig,
  User,
  Role,
  ClinicId,
  Incident,
  IncidentType,
  IncidentSeverity,
  IncidentStatus,
  Complaint,
  ComplaintSeverity,
  ComplaintStatus,
  Amendment,
  GPLetter,
  GPLetterStatus,
  GPLetterTemplate,
  GPCommunicationLifecycle,
  MondayItem,
  MondayBoardState,
  ClinicalEscalationFlag,
  // Wave 3 additions
  ClinicalNote,
  SlaBreach,
  SlaBreachEntityType,
  // Wave 4 additions
  PharmacyCommThread,
  PharmacyCommMessage,
  PharmacyCommAnchorType,
} from "@/lib/api/mock";
